apiVersion: v1
kind: Secret

metadata:
  name: makeup-secret
  namespace: makeup-app

type: Opaque

stringData:
  DB_USER: "admin"
  DB_PASSWORD: "YOUR_DB_PASSWORD"
  SNS_TOPIC_ARN: "YOUR_SNS_TOPIC_ARN"
  SQS_QUEUE_URL: "YOUR_SQS_QUEUE_URL"
